### ISSUE TITLE
Is not possible to edit an existing table

### ISSUE THREAD

**Issue by felipep** [ragi96/table-field#2]
I tried to use this plugin in Kirby 3.3.6 

Add a table worked as expected.
![Screenshot 2020-04-29 09 52 25](https://user-images.githubusercontent.com/358557/80572926-6016e380-89ff-11ea-93f4-e5cdc4efd5b1.png)

The data was saved as yml.
![Screenshot 2020-04-29 09 52 34](https://user-images.githubusercontent.com/358557/80572964-6f962c80-89ff-11ea-8f3a-adf5cbee59b4.png)

But to edit the data was not possible, wrong display, functions not available 
![Screenshot 2020-04-29 09 52 53](https://user-images.githubusercontent.com/358557/80573000-8046a280-89ff-11ea-8b73-7b03774a82b8.png)
![Screenshot 2020-04-29 09 55 23](https://user-images.githubusercontent.com/358557/80573033-8ccafb00-89ff-11ea-89d4-083c7e07a126.png)

**Comment by jesuismaxime** [comment]
Is there any roadmap for that fix? Kind of annoying (does that with Kirby 3.3.3 too).

**Comment by felipep** [comment]
@ragi96 I cloned the "dev-master" version of the repository and the problem is solved for me, thanks.

**Comment by ragi96** [comment]
Fixed in latest release
